name: Build and Update

on:
  push:
    tags:
      - v**

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Set Tag Variable
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Checkout Compiler
        uses: actions/checkout@v4
        with:
          repository: librasn/compiler
          path: $HOME/compiler

      - name: Install Rust Toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: '1.77.2'
          target: wasm32-unknown-unknown

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Checkout Pages Src
        uses: actions/checkout@v4
        with:
          ref: main
          path: $HOME/web

      - name: Build for WASM
        working-directory: $HOME/compiler
        run: |
          cargo build -p rasn-compiler --target wasm32-unknown-unknown --release    
          cargo install -f wasm-bindgen-cli --version 0.2.92
          wasm-bindgen --out-dir $HOME/web/src/lib/compiler --target web ./target/wasm32-unknown-unknown/release/rasn_compiler.wasm

      - name: Install Page Dependencies
        working-directory: $HOME/web
        run: npm install

      - name: Build Page
        working-directory: $HOME/web
        run: npm run build

      - name: Push WASM Updates
        working-directory: $HOME/web
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "chore: release $RELEASE_VERSION"
          git push
